EURO600 = ['SOF.BR', 'CLNX.MC', 'AAL.L', 'ANDR.VI', 'AKRBP.OL', 'SIE.DE', 'CPR.MI', 'TUI1.DE', 'EOAN.DE', 'KBC.BR', 'LHA.DE', 
           'TECN.SW', 'EMG.L', 'STMMI.MI', 'INDU-C.ST', 'HOLM-B.ST', 'WTB.L', 'AUTO.L', 'IBE.MC', 'NIBE-B.ST', 'JDEP.AS', 'COFB.BR', 
           'BKT.MC', 'FABG.ST', 'SK.PA', 'HO.PA', 'BIRG.IR', 'AFX.DE', 'THULE.ST', 'KGH.WA', 'SLHN.SW', 'DIM.PA', 'ANE.MC', 'DSY.PA', 
           'HLN.L', 'BVI.PA', 'RTO.L', 'TKWY.AS', 'COLO-B.CO', 'EVD.DE', 'P911.DE', 'ELIS.PA', 'CNA.L', 'SKF-B.ST', 'ABN.AS', 'FRO.OL', 
           'WIHL.ST', 'AMUN.PA', 'FUTR.L', 'NEM.DE', 'NESN.SW', 'RWE.DE', 'ASM.AS', 'INVE-B.ST', 'ZURN.SW', 'BB.PA', 'MUV2.DE', 'GAW.L', 
           'LISN.SW', 'WKL.AS', 'BEIJ-B.ST', 'BBVA.MC', 'FHZN.SW', 'GFTU.L', 'CCH.L', 'CARL-B.CO', 'TATE.L', 'WLN.PA', 'OCDO.L', 
           'AMBU-B.CO', 'BA.L', 'PUB.PA', 'ENOG.L', 'LEG.DE', 'OMV.VI', 'ARGX.BR', 'ABDN.L', 'RBREW.CO', 'AIXA.DE', 'WDP.BR', 'KER.PA', 
           'EDP.LS', 'BC8.DE', 'PRU.L', 'HEN3.DE', 'TEL2-B.ST', 'SU.PA', 'BEAN.SW', 'ROR.L', 'STJ.L', 'DBK.DE', 'GTT.PA', 'SCT.L', 
           'BEZ.L', 'CABK.MC', 'FGR.PA', 'KGX.DE', 'WALL-B.ST', 'DLN.L', 'SGRO.L', 'CTEC.L', 'STB.OL', 'WOSG.L', 'NOVO-B.CO', 'PGHN.SW', 
           'SGO.PA', 'SOP.PA', 'ENGI.PA', 'CTM.ST', 'EMSN.SW', 'ARCAD.AS', 'CS.PA', 'SOI.PA', 'ISP.MI', 'BMW.DE', 'INVP.L', 'COL.MC', 
           'BME.L', 'DG.PA', 'RKT.L', 'GLE.PA', 'VOLCAR-B.ST', 'DNB.OL', 'CON.DE', 'UTDI.DE', 'DTE.DE', 'SMIN.L', 'TEN.MI', 'IMI.L', 
           'ICG.L', 'DSV.CO', 'RHM.DE', 'ADM.L', 'IG.MI', 'VTY.L', 'HEIA.AS', 'FPE.DE', 'BAER.SW', 'UTG.L', 'SAN.PA', 'HWDN.L', 'FBK.MI', 
           'TRN.MI', 'AT1.DE', 'LOGN.SW', 'ALE.WA', 'AAK.ST', 'AXFO.ST', 'NEL.OL', 'SRG.MI', 'A2A.MI', 'AHT.L', 'ENG.MC', 'DRX.L', 'RED.MC', 
           'ZAL.DE', 'NWG.L', 'FER.AS', 'SBRY.L', 'ENR.DE', 'KNEBV.HE', 'SRT.DE', 'SPX.L', 'ADEN.SW', 'MRO.L', 'QIA.DE', 'BARN.SW', 
           'VWS.CO', 'LUND-B.ST', 'ULVR.L', 'INW.MI', 'SREN.SW', 'IMB.L', 'IMCD.AS', 'ROCK-B.CO', 'ATCO-A.ST', 'SGSN.SW', 'ERIC-B.ST', 
           'NOVN.SW', 'SCR.PA', 'HNR1.DE', 'EXO.AS', 'AGN.AS', 'GETI-B.ST', 'DB1.DE', 'SAP.DE', 'TLX.DE', 'ANA.MC', 'MRL.MC', 'VAL.PA', 
           'RI.PA', 'GLEN.L', 'LIFCO-B.ST', 'AF.PA', 'WISE.L', 'BANB.SW', 'SDR.L', 'CRDA.L', 'AGS.BR', 'RIO.L', 'HEXA-B.ST', 'BKW.SW', 
           'LLOY.L', 'DPLM.L', 'ENI.MI', 'GXI.DE', 'VALMT.HE', 'UPM.HE', 'DCC.L', 'FRE.DE', 'GMAB.CO', 'GSK.L', 'AMS.MC', 'SESG.PA', 
           'VOLV-B.ST', 'NESTE.HE', 'EQNR.OL', 'PEO.WA', 'TKA.DE', 'CAP.PA', 'BESI.AS', 'HEIO.AS', 'PSPN.SW', 'CCC.L', 'ATE.PA', 'NEXI.MI', 
           'SIKA.SW', 'MRK.DE', 'YAR.OL', 'DTG.DE', 'PZU.WA', 'SIGN.SW', 'FNTN.DE', 'VOW3.DE', 'AMP.MI', 'VIE.PA', 'CRH.L', 'ALK-B.CO', 
           'SAFE.L', 'VOD.L', 'FRVIA.PA', 'KESKOB.HE', 'DEMANT.CO', 'G1A.DE', 'INCH.L', 'RF.PA', 'TEL.OL', 'SOBI.ST', 'BALD-B.ST', 'REP.MC', 
           'HEI.DE', 'KNIN.SW', 'SHL.DE', 'WRT1V.HE', 'ABF.L', 'AENA.MC', 'AM.PA', 'EVT.DE', 'INGA.AS', 'GEBN.SW', 'TEP.PA', 'MC.PA', 
           'MOWI.OL', 'SAAB-B.ST', 'EL.PA', 'VID.MC', 'DSFIR.AS', 'SHB-A.ST', 'SAN.MC', 'RACE.MI', 'BOL.ST', 'EPI-A.ST', 'SXS.L', 
           'SSAB-B.ST', 'TEMN.SW', 'GALP.LS', 'LONN.SW', 'NHY.OL', 'WCH.DE', 'ABI.BR', 'RR.L', 'EN.PA', 'EDEN.PA', 'TELIA.ST', 'VRLA.PA', 
           'ACS.MC', 'ERF.PA', 'HTRO.ST', 'BG.VI', 'ALLN.SW', 'BT-A.L', 'RXL.PA', 'ACKB.BR', 'TTE.PA', 'LATO-B.ST', 'GL9.IR', 'HBR.L', 
           'IP.MI', 'NTGY.MC', 'AC.PA', 'LSEG.L', 'SHEL.L', 'EVK.DE', 'GJF.OL', 'CLN.SW', 'BEI.DE', 'EMBRAC-B.ST', 'ORSTED.CO', 'SEB-A.ST', 
           'ORK.OL', 'SAF.PA', 'UHR.SW', 'SYDB.CO', 'OR.PA', 'SVT.L', 'ENEL.MI', 'SPIE.PA', 'SAND.ST', 'SKA-B.ST', 'UCB.BR', 'SCMN.SW', 
           'DHL.DE', 'SY1.DE', 'ALFA.ST', 'ITX.MC', 'AKZA.AS', 'STAN.L', 'MTX.DE', 'BAS.DE', 'RYA.IR', 'IFX.DE', 'PKN.WA', 'BUCN.SW', 
           'DIA.MI', 'BOL.PA', '1COV.DE', 'ALLFG.AS', 'GIVN.SW', 'SAMPO.HE', 'BAVA.CO', 'SALM.OL', 'EXPN.L', 'SOLB.BR', 'MT.AS', 'BNP.PA', 
           'ORA.PA', 'INF.L', 'TE.PA', 'BALN.SW', 'NOD.OL', 'MAERSK-B.CO', 'CMBN.SW', 'ESSITY-B.ST', 'MONC.MI', 'ANTO.L', 'LXS.DE', 'CA.PA', 
           'UU.L', 'GRF.MC', 'SAGA-B.ST', 'UBI.PA', 'STLAM.MI', 'RMV.L', 'IAG.L', 'NOKIA.HE', 'MNDI.L', 'DKSH.SW', 'HOLN.SW', 'PKO.WA', 
           'NXT.L', 'ASRNL.AS', 'SDF.DE', 'SSE.L', 'HER.MI', 'BYG.L', 'IHG.L', 'AMS.SW', 'DNP.WA', 'UBSG.SW', 'AALB.AS', 'VACN.SW', 
           'LAGR-B.ST', 'FME.DE', 'CFR.SW', 'DANSKE.CO', 'RNO.PA', 'PSN.L', 'BWY.L', 'CBK.DE', 'AI.PA', 'SAB.MC', 'LAND.L', 'EQT.ST', 
           'ALC.SW', 'VIV.PA', 'GET.PA', 'NG.L', 'KINV-B.ST', 'BATS.L', 'EDPR.LS', 'JMAT.L', 'ELISA.HE', 'AD.AS', 'G24.DE', 'REY.MI', 
           'KOG.OL', 'MB.MI', 'BAKKA.OL', 'BN.PA', 'KPN.AS', 'IPN.PA', 'BAMI.MI', 'BNZL.L', 'SN.L', 'ROG.SW', 'BC.MI', 'VIS.MC', 'RS1.L', 
           'LGEN.L', 'TSCO.L', 'BRBY.L', 'BPE.MI', 'SECT-B.ST', 'NN.AS', 'WPP.L', 'FAG.ST', 'LOTB.BR', 'BP.L', 'CDI.PA', 'SCA-B.ST', 
           'ALO.PA', 'ACA.PA', 'MNG.L', 'RAA.DE', 'TIETO.HE', 'DIE.BR', 'VOE.VI', 'HSX.L', 'LDO.MI', 'RILBA.CO', 'SGE.L', 'REL.L', 'IGG.L', 
           'SUBC.OL', 'MBG.DE', 'DGE.L', 'KGF.L', 'SOON.SW', 'RAND.AS', 'FORTUM.HE', 'PUM.DE', 'SWED-A.ST', 'BILL.ST', 'EVO.ST', 'SBB-B.ST', 
           'AED.BR', 'TREL-B.ST', 'MKS.L', 'AZN.L', 'SPSN.SW', 'HELN.SW', 'AZM.MI', 'LR.PA', 'SW.PA', 'STERV.HE', 'BLND.L', 'AV.L', 
           'PSON.L', 'LPP.WA', 'ELUX-B.ST', 'PAH3.DE', 'TW.L', 'BAYN.DE', 'OCI.AS', 'NDA-FI.HE', 'HM-B.ST', 'ML.PA', 'HLMA.L', 'BKG.L', 
           'STMN.SW', 'FLTR.L', 'ASML.AS', 'VNA.DE', 'UMI.BR', 'ORNBV.HE', 'ELE.MC', 'JMT.LS', 'ENX.PA', 'KBX.DE', 'PHIA.AS', 'BOSS.DE', 
           'AZA.ST', 'GNS.L', 'PHNX.L', 'LMP.L', 'III.L', 'GRG.L', 'OSB.L', 'CBG.L', 'PST.MI', 'ITRK.L', 'GBLB.BR', 'KOJAMO.HE', 
           'PNDORA.CO', 'PRY.MI', 'ADDT-B.ST', 'HAS.L', 'ELI.BR', 'TEF.MC', 'ENT.L', 'TIT.MI', 'SFZN.SW', 'CPG.L', 'SCHN.SW', 'GFC.PA', 
           'HUH1V.HE', 'BCVN.SW', 'HSBA.L', 'HIK.L', 'ASSA-B.ST', 'AKE.PA', 'TPK.L', 'ADYEN.AS', 'ALV.DE', 'WEIR.L', 'PRX.AS', 
           'LIGHT.AS', 'TOM.OL', 'WIE.VI', 'COV.PA', 'GN.CO', 'EBS.VI', 'SINCH.ST', 'ITV.L', 'JYSK.CO', 'AIR.PA', 'UCG.MI', 'TRYG.CO', 
           'UMG.AS', 'BNR.DE', 'VER.VI', 'NOBI.ST', 'SWEC-B.ST', 'DWL.L', 'ABBN.SW', 'RUI.PA', 'SECU-B.ST', 'ISS.CO', 'NSIS-B.CO', 
           'ADS.DE', 'BBOX.L', 'BARC.L', 'PNN.L', 'RCO.PA', 'REC.MI', 'DHER.DE', 'METSO.HE', 'NEX.PA', 'G.MI', 'RMS.PA', 'INDV.L']
